METATAG_KEYWORDS = [
  "Tsunami",
  "Earthquake",
  "Drought",
  "Preparedness",
  "Preparedness Kit",
  "Make a Kit",
  "Get Prepared",
  "Ready Gov",
  "Ready",
  "San Jose",
  "San Jose Firefighters",
  "San Jose Fire Department",
  "First Responders",
  "resilience",
  "Fire",
  "Shelter In Place",
  "Evacuation",
  "Prepared",
  "Make a Plan",
  "San Jose Crisis",
  "Disaster Plan",
  "San Jose Disaster",
  "Emergency",
  "San Jose Emergency",
  "Emergency Plan",
  "Emergency Kit",
  "Family Preparedness",
  "Personal Preparedness",
  "First Responder Preparedness",
  "Pet Preparedness",
  "96 Hours",
  "96 Hour Kit",
  "Storm",
  "Flood",
  "Flooding",
  "Terrorism",
  "IED in San Jose",
  "Duct Tape",
  "San Jose",
  "South Bay",
  "West Valley",
  "North San Jose",
  "East San Jose",
  "North Valley",
  "Santa Teresa",
  "Blossom Valley",
  "Alviso",
  "East Foothills",
  "Edenvale - Seven Trees",
  "Fairgrounds",
  "Willow Glen",
  "Edenvale",
  "Evergreen",
  "Central San Jose",
  "Alum Rock",
  "Berryessa",
  "Cambrian",
  "Almaden",
  "South San Jose",
  "Private Sector preparedness"
].join(',')