---
development:
  cloud_name: hee3ety71
  api_key: '136595561532171'
  api_secret: krFmMw4Mai-5l7gLXj7xTfHgWfk
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hee3ety71
  api_key: '136595561532171'
  api_secret: krFmMw4Mai-5l7gLXj7xTfHgWfk
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hee3ety71
  api_key: '136595561532171'
  api_secret: krFmMw4Mai-5l7gLXj7xTfHgWfk
  enhance_image_tag: true
  static_image_support: false